In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [21]:
df = pd.read_csv("data.csv")
df.head()

make fuel-type aspiration num-of-doors   body-style drive-wheels  \
0  alfa-romero       gas        std          two  convertible          rwd   
1  alfa-romero       gas        std          two  convertible          rwd   
2  alfa-romero       gas        std          two    hatchback          rwd   
3         audi       gas        std         four        sedan          fwd   
4         audi       gas        std         four        sedan          4wd   

  engine-location  wheel-base  length  width  ...  engine-size  fuel-system  \
0           front        88.6   168.8   64.1  ...          130         mpfi   
1           front        88.6   168.8   64.1  ...          130         mpfi   
2           front        94.5   171.2   65.5  ...          152         mpfi   
3           front        99.8   176.6   66.2  ...          109         mpfi   
4           front        99.4   176.6   66.4  ...          136         mpfi   

   bore stroke  compression-ratio horsepower  peak-rpm  city-mpg  highway-mpg  \
0  3.47   2.68                9.0        111      5000        21           27   
1  3.47   2.68                9.0        111      5000        21           27   
2  2.68   3.47                9.0        154      5000        19           26   
3  3.19   3.40               10.0        102      5500        24           30   
4  3.19   3.40                8.0        115      5500        18           22   

   price  
0  13495  
1  16500  
2  16500  
3  13950  
4  17450  

[5 rows x 24 columns]

In [22]:
df.shape

(193, 24)

In [23]:
df._get_numeric_data()

wheel-base  length  width  height  curb-weight  engine-size  bore  \
0          88.6   168.8   64.1    48.8         2548          130  3.47   
1          88.6   168.8   64.1    48.8         2548          130  3.47   
2          94.5   171.2   65.5    52.4         2823          152  2.68   
3          99.8   176.6   66.2    54.3         2337          109  3.19   
4          99.4   176.6   66.4    54.3         2824          136  3.19   
..          ...     ...    ...     ...          ...          ...   ...   
188       109.1   188.8   68.9    55.5         2952          141  3.78   
189       109.1   188.8   68.8    55.5         3049          141  3.78   
190       109.1   188.8   68.9    55.5         3012          173  3.58   
191       109.1   188.8   68.9    55.5         3217          145  3.01   
192       109.1   188.8   68.9    55.5         3062          141  3.78   

     stroke  compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg  \
0      2.68                9.0         111      5000        21           27   
1      2.68                9.0         111      5000        21           27   
2      3.47                9.0         154      5000        19           26   
3      3.40               10.0         102      5500        24           30   
4      3.40                8.0         115      5500        18           22   
..      ...                ...         ...       ...       ...          ...   
188    3.15                9.5         114      5400        23           28   
189    3.15                8.7         160      5300        19           25   
190    2.87                8.8         134      5500        18           23   
191    3.40               23.0         106      4800        26           27   
192    3.15                9.5         114      5400        19           25   

     price  
0    13495  
1    16500  
2    16500  
3    13950  
4    17450  
..     ...  
188  16845  
189  19045  
190  21485  
191  22470  
192  22625  

[193 rows x 14 columns]

In [24]:
df.select_dtypes(include=['object'])

make fuel-type aspiration num-of-doors   body-style drive-wheels  \
0    alfa-romero       gas        std          two  convertible          rwd   
1    alfa-romero       gas        std          two  convertible          rwd   
2    alfa-romero       gas        std          two    hatchback          rwd   
3           audi       gas        std         four        sedan          fwd   
4           audi       gas        std         four        sedan          4wd   
..           ...       ...        ...          ...          ...          ...   
188        volvo       gas        std         four        sedan          rwd   
189        volvo       gas      turbo         four        sedan          rwd   
190        volvo       gas        std         four        sedan          rwd   
191        volvo    diesel      turbo         four        sedan          rwd   
192        volvo       gas      turbo         four        sedan          rwd   

    engine-location engine-type num-of-cylinders fuel-system  
0             front        dohc             four        mpfi  
1             front        dohc             four        mpfi  
2             front        ohcv              six        mpfi  
3             front         ohc             four        mpfi  
4             front         ohc             five        mpfi  
..              ...         ...              ...         ...  
188           front         ohc             four        mpfi  
189           front         ohc             four        mpfi  
190           front        ohcv              six        mpfi  
191           front         ohc              six         idi  
192           front         ohc             four        mpfi  

[193 rows x 10 columns]

In [25]:
col =list(df.columns)
df.dtypes

make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower             int64
peak-rpm               int64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [26]:
list_object=list()
for j in col:
    if (df[j].dtype=='object'):
        le = LabelEncoder().fit(df[j])
        df[j]=le.transform(df[j])
        
    


In [27]:
le.inverse_transform(df['num-of-doors'])

array(['2bbl', '2bbl', '2bbl', '1bbl', '1bbl', '2bbl', '1bbl', '1bbl',
       '1bbl', '2bbl', '1bbl', '2bbl', '1bbl', '1bbl', '1bbl', '2bbl',
       '1bbl', '2bbl', '2bbl', '1bbl', '2bbl', '2bbl', '2bbl', '1bbl',
       '1bbl', '1bbl', '1bbl', '2bbl', '2bbl', '2bbl', '2bbl', '2bbl',
       '2bbl', '1bbl', '1bbl', '2bbl', '2bbl', '1bbl', '1bbl', '1bbl',
       '2bbl', '1bbl', '2bbl', '1bbl', '1bbl', '2bbl', '2bbl', '2bbl',
       '2bbl', '1bbl', '1bbl', '2bbl', '1bbl', '2bbl', '1bbl', '1bbl',
       '1bbl', '1bbl', '1bbl', '1bbl', '2bbl', '1bbl', '1bbl', '2bbl',
       '1bbl', '2bbl', '2bbl', '2bbl', '2bbl', '2bbl', '2bbl', '2bbl',
       '2bbl', '2bbl', '2bbl', '2bbl', '1bbl', '1bbl', '1bbl', '1bbl',
       '2bbl', '2bbl', '2bbl', '1bbl', '1bbl', '2bbl', '2bbl', '1bbl',
       '1bbl', '2bbl', '1bbl', '1bbl', '1bbl', '1bbl', '1bbl', '2bbl',
       '2bbl', '2bbl', '1bbl', '1bbl', '1bbl', '1bbl', '1bbl', '1bbl',
       '1bbl', '1bbl', '1bbl', '1bbl', '1bbl', '2bbl', '2bbl', '1bbl',
      

In [28]:
df.head()

        

make  fuel-type  aspiration  num-of-doors  body-style  drive-wheels  \
0     0          1           0             1           0             2   
1     0          1           0             1           0             2   
2     0          1           0             1           2             2   
3     1          1           0             0           3             1   
4     1          1           0             0           3             0   

   engine-location  wheel-base  length  width  ...  engine-size  fuel-system  \
0                0        88.6   168.8   64.1  ...          130            4   
1                0        88.6   168.8   64.1  ...          130            4   
2                0        94.5   171.2   65.5  ...          152            4   
3                0        99.8   176.6   66.2  ...          109            4   
4                0        99.4   176.6   66.4  ...          136            4   

   bore  stroke  compression-ratio  horsepower  peak-rpm  city-mpg  \
0  3.47    2.68                9.0         111      5000        21   
1  3.47    2.68                9.0         111      5000        21   
2  2.68    3.47                9.0         154      5000        19   
3  3.19    3.40               10.0         102      5500        24   
4  3.19    3.40                8.0         115      5500        18   

   highway-mpg  price  
0           27  13495  
1           27  16500  
2           26  16500  
3           30  13950  
4           22  17450  

[5 rows x 24 columns]

In [29]:
df.dtypes

make                   int32
fuel-type              int32
aspiration             int32
num-of-doors           int32
body-style             int32
drive-wheels           int32
engine-location        int32
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type            int32
num-of-cylinders       int32
engine-size            int64
fuel-system            int32
bore                 float64
stroke               float64
compression-ratio    float64
horsepower             int64
peak-rpm               int64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [30]:
x = df.iloc[:,:23]
x.head()

make  fuel-type  aspiration  num-of-doors  body-style  drive-wheels  \
0     0          1           0             1           0             2   
1     0          1           0             1           0             2   
2     0          1           0             1           2             2   
3     1          1           0             0           3             1   
4     1          1           0             0           3             0   

   engine-location  wheel-base  length  width  ...  num-of-cylinders  \
0                0        88.6   168.8   64.1  ...                 2   
1                0        88.6   168.8   64.1  ...                 2   
2                0        94.5   171.2   65.5  ...                 3   
3                0        99.8   176.6   66.2  ...                 2   
4                0        99.4   176.6   66.4  ...                 1   

   engine-size  fuel-system  bore  stroke  compression-ratio  horsepower  \
0          130            4  3.47    2.68                9.0         111   
1          130            4  3.47    2.68                9.0         111   
2          152            4  2.68    3.47                9.0         154   
3          109            4  3.19    3.40               10.0         102   
4          136            4  3.19    3.40                8.0         115   

   peak-rpm  city-mpg  highway-mpg  
0      5000        21           27  
1      5000        21           27  
2      5000        19           26  
3      5500        24           30  
4      5500        18           22  

[5 rows x 23 columns]

In [31]:
y = df.iloc[:,23:]
y.head()

price
0  13495
1  16500
2  16500
3  13950
4  17450

In [32]:
x_train ,x_test ,y_train ,y_test = train_test_split(x,y, test_size =0.2 ,random_state=1)

In [33]:
len(x_train)
len(y_train)

154

In [34]:
obj =LinearRegression().fit(x_train,y_train)

In [35]:
obj.coef_

array([[-1.79078583e+02,  6.24678581e+03,  2.28911312e+03,
        -2.63104146e+02, -6.13849819e+02,  7.61985329e+02,
         1.12065806e+04, -3.83718223e+00,  2.95479372e+01,
         3.79330024e+02,  3.42338537e+02,  2.55536204e+00,
        -2.37477710e+02, -1.70746820e+03,  1.22532160e+02,
         2.19827251e+02, -2.45064889e+03, -4.09928651e+03,
         5.30813248e+02,  1.53305078e+01,  1.34148398e+00,
        -9.21761064e+01,  2.16677995e+02]])

In [36]:
obj.intercept_

array([-53890.32617924])

In [37]:
obj.predict(x_test)

array([[28600.81131955],
       [ 6757.07703221],
       [11014.89107644],
       [ 9735.61577332],
       [16021.90080215],
       [17001.72588814],
       [20146.40061469],
       [ 8364.29078634],
       [ 7887.38068561],
       [14485.00926446],
       [ 8733.03810045],
       [ 6408.35361458],
       [ 6697.69024069],
       [27559.10994361],
       [18766.32771524],
       [ 6634.2932423 ],
       [ 6561.09525134],
       [10676.66135006],
       [ 7018.8104105 ],
       [ 9712.87193646],
       [ 7313.19943099],
       [16266.95723587],
       [18972.80018895],
       [16367.97642706],
       [14762.6494665 ],
       [14504.95539653],
       [ 9600.66726065],
       [ 6338.54994893],
       [10676.66135006],
       [ 7723.29580561],
       [18932.30766602],
       [34004.28574904],
       [26187.79606267],
       [ 6061.11900732],
       [16194.35487355],
       [25263.40023414],
       [ 8666.87039132],
       [ 8285.43863532],
       [ 8844.46907018]])

In [38]:
obj.score(x_test,y_test)

0.9039629397377748

In [39]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, **options)
    Split arrays or matrices into random train and test subsets
    
    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float, int or None, optional (default=None)
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. If ``train_s